/* elf.h — parse and load a 32-bit ELF executable already sitting in memory.
 *
 * "Already in memory" is the key phrase: with no filesystem yet (M9), a
 * program's bytes have to come from somewhere else — for now, embedded
 * straight into the kernel image at build time. The parsing/loading logic
 * here doesn't care where the bytes came from, though; swapping the source
 * for "read this file off disk" later is a small change, not a rewrite. */
#ifndef ELF_H
#define ELF_H

#include <stdint.h>

/* The embedded test program's raw bytes, generated by `ld -r -b binary`
 * from userprogs/hello.elf (see the Makefile). GNU ld invents these symbol
 * names from the file's path — `start`/`end` bracket the bytes, `size` is a
 * linker ABSOLUTE symbol (its VALUE is the byte count, there's no data to
 * take the address of, hence it's declared as an array of unknown extent
 * rather than a pointer). */
extern uint8_t _binary_hello_elf_start[];
extern uint8_t _binary_hello_elf_end[];

/* Returns 1 and calls into the program's entry point if `data` is a valid
 * ELF32 executable this loader understands. Returns 0 (and prints why) on
 * anything it can't or won't run. This function only returns at all if the
 * ELF failed to load — a successful load jumps away and never comes back
 * (there's no process to return TO yet; that needs a scheduler, M8+). */
int elf_load(const uint8_t* data);

#endif
